# Generated by Django 3.1.7 on 2021-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IotDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(null=True)),
                ('iot_device_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50, null=True)),
                ('device_status', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'iot_devices',
            },
        ),
        migrations.CreateModel(
            name='operatorDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='iot_devices.iotdevice')),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_device',
            },
        ),
    ]
