# Generated by Django 3.1.3 on 2021-04-06 08:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('iot_devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='user_id',
        ),
    ]
