# Generated by Django 3.1.3 on 2021-04-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('iot_devices', '0003_operatordevices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatordevices',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iot_devices.iotdevice',
                                    unique=True),
        ),
    ]
