# Generated by Django 3.1.3 on 2021-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_devices', '0004_auto_20210406_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotdevice',
            name='device_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
