# Generated by Django 3.1.7 on 2021-04-13 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import patients.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_full_name', models.CharField(max_length=50)),
                ('patient_dob', models.DateField()),
                ('patient_email', models.EmailField(max_length=150, unique=True, validators=[patients.models.validate_email])),
                ('patient_contact', models.CharField(max_length=12, validators=[patients.models.validatecontact])),
                ('patient_location', models.CharField(max_length=50)),
                ('patient_gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients_table',
            },
        ),
        migrations.CreateModel(
            name='Patientoperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('assign', 'assign'), ('removed', 'removed')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'patient_operator',
            },
        ),
    ]
