# Generated by Django 3.1.7 on 2021-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprediction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampledata',
            name='mode',
            field=models.CharField(choices=[('autoscope', 'autoscope'), ('ace_it', 'ace_it')], default='autoscope', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sampledata',
            name='image_name',
            field=models.CharField(max_length=255),
        ),
    ]
